name: Draft Release

on:
  push:
    tags: ["*"]

jobs:
  draft-release:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Draft Release
        run: |
          gh release create ${GITHUB_REF##*/} --title "${GITHUB_REF##*/}" --draft --generate-notes --prerelease
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
