name: Publish to NPM

on:
  workflow_call:
    inputs:
      github_ref:
        description: 'The branch or tag ref that triggered the workflow'
        required: true
        type: string

jobs:
  npm-publish:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.github_ref }}

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
          cache: yarn

      - name: Initialize Project
        run: |
          yarn install --immutable
          yarn add --dev lerna
          yarn build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: Publish Project
        run: |
          # Prevent `git commit error` when running `lerna version`
          # It will not pushed to GitHub. It is ephemeral
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

          # Workaround to not include changes by adding lerna
          git reset --hard HEAD

          lerna version 0.0.0-${{ inputs.github_ref }}.$(git rev-parse --short HEAD) --no-push --yes
          lerna publish from-git --dist-tag ci --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
